<?php declare(strict_types = 1);

namespace Markette\Gopay\Api;

/**
 * Trida obsahuje kody pro jednotlive staty
 */
class CountryCode
{

	public const ABW = 'ABW'; //Aruba
	public const AFG = 'AFG'; //Afghanistan
	public const AGO = 'AGO'; //Angola
	public const AIA = 'AIA'; //Anguilla
	public const ALA = 'ALA'; //Åland Islands
	public const ALB = 'ALB'; //Albania
	public const ARE = 'ARE'; //United Arab Emirates
	public const ARG = 'ARG'; //Argentina
	public const ARM = 'ARM'; //Armenia
	public const ASM = 'ASM'; //American Samoa
	public const ATA = 'ATA'; //Antarctica
	public const ATF = 'ATF'; //French Southern Territories
	public const ATG = 'ATG'; //Antigua and Barbuda
	public const AUS = 'AUS'; //Australia
	public const AUT = 'AUT'; //Austria
	public const AZE = 'AZE'; //Azerbaijan
	public const BDI = 'BDI'; //Burundi
	public const BEL = 'BEL'; //Belgium
	public const BEN = 'BEN'; //Benin
	public const BES = 'BES'; //Bonaire, Sint Eustatius and Saba
	public const BFA = 'BFA'; //Burkina Faso
	public const BGD = 'BGD'; //Bangladesh
	public const BGR = 'BGR'; //Bulgaria
	public const BHR = 'BHR'; //Bahrain
	public const BHS = 'BHS'; //Bahamas
	public const BIH = 'BIH'; //Bosnia and Herzegovina
	public const BLM = 'BLM'; //Saint Barthélemy
	public const BLR = 'BLR'; //Belarus
	public const BLZ = 'BLZ'; //Belize
	public const BMU = 'BMU'; //Bermuda
	public const BOL = 'BOL'; //Bolivia, Plurinational State of
	public const BRA = 'BRA'; //Brazil
	public const BRB = 'BRB'; //Barbados
	public const BRN = 'BRN'; //Brunei Darussalam
	public const BTN = 'BTN'; //Bhutan
	public const BVT = 'BVT'; //Bouvet Island
	public const BWA = 'BWA'; //Botswana
	public const CAF = 'CAF'; //Central African Republic
	public const CAN = 'CAN'; //Canada
	public const CCK = 'CCK'; //Cocos (Keeling) Islands
	public const CHE = 'CHE'; //Switzerland
	public const CHL = 'CHL'; //Chile
	public const CHN = 'CHN'; //China
	public const CIV = 'CIV'; //Côte d'Ivoire
	public const CMR = 'CMR'; //Cameroon
	public const COD = 'COD'; //Congo, the Democratic Republic of the
	public const COG = 'COG'; //Congo
	public const COK = 'COK'; //Cook Islands
	public const COL = 'COL'; //Colombia
	public const COM = 'COM'; //Comoros
	public const CPV = 'CPV'; //Cape Verde
	public const CRI = 'CRI'; //Costa Rica
	public const CUB = 'CUB'; //Cuba
	public const CUW = 'CUW'; //Curaçao
	public const CXR = 'CXR'; //Christmas Island
	public const CYM = 'CYM'; //Cayman Islands
	public const CYP = 'CYP'; //Cyprus
	public const CZE = 'CZE'; //Czech Republic
	public const DEU = 'DEU'; //Germany
	public const DJI = 'DJI'; //Djibouti
	public const DMA = 'DMA'; //Dominica
	public const DNK = 'DNK'; //Denmark
	public const DOM = 'DOM'; //Dominican Republic
	public const DZA = 'DZA'; //Algeria
	public const ECU = 'ECU'; //Ecuador
	public const EGY = 'EGY'; //Egypt
	public const ERI = 'ERI'; //Eritrea
	public const ESH = 'ESH'; //Western Sahara
	public const ESP = 'ESP'; //Spain
	public const EST = 'EST'; //Estonia
	public const ETH = 'ETH'; //Ethiopia
	public const FIN = 'FIN'; //Finland
	public const FJI = 'FJI'; //Fiji
	public const FLK = 'FLK'; //Falkland Islands (Malvinas)
	public const FRA = 'FRA'; //France
	public const FRO = 'FRO'; //Faroe Islands
	public const FSM = 'FSM'; //Micronesia, Federated States of
	public const GAB = 'GAB'; //Gabon
	public const GBR = 'GBR'; //United Kingdom
	public const GEO = 'GEO'; //Georgia
	public const GGY = 'GGY'; //Guernsey
	public const GHA = 'GHA'; //Ghana
	public const GIB = 'GIB'; //Gibraltar
	public const GIN = 'GIN'; //Guinea
	public const GLP = 'GLP'; //Guadeloupe
	public const GMB = 'GMB'; //Gambia
	public const GNB = 'GNB'; //Guinea-Bissau
	public const GNQ = 'GNQ'; //Equatorial Guinea
	public const GRC = 'GRC'; //Greece
	public const GRD = 'GRD'; //Grenada
	public const GRL = 'GRL'; //Greenland
	public const GTM = 'GTM'; //Guatemala
	public const GUF = 'GUF'; //French Guiana
	public const GUM = 'GUM'; //Guam
	public const GUY = 'GUY'; //Guyana
	public const HKG = 'HKG'; //Hong Kong
	public const HMD = 'HMD'; //Heard Island and McDonald Islands
	public const HND = 'HND'; //Honduras
	public const HRV = 'HRV'; //Croatia
	public const HTI = 'HTI'; //Haiti
	public const HUN = 'HUN'; //Hungary
	public const IDN = 'IDN'; //Indonesia
	public const IMN = 'IMN'; //Isle of Man
	public const IND = 'IND'; //India
	public const IOT = 'IOT'; //British Indian Ocean Territory
	public const IRL = 'IRL'; //Ireland
	public const IRN = 'IRN'; //Iran, Islamic Republic of
	public const IRQ = 'IRQ'; //Iraq
	public const ISL = 'ISL'; //Iceland
	public const ISR = 'ISR'; //Israel
	public const ITA = 'ITA'; //Italy
	public const JAM = 'JAM'; //Jamaica
	public const JEY = 'JEY'; //Jersey
	public const JOR = 'JOR'; //Jordan
	public const JPN = 'JPN'; //Japan
	public const KAZ = 'KAZ'; //Kazakhstan
	public const KEN = 'KEN'; //Kenya
	public const KGZ = 'KGZ'; //Kyrgyzstan
	public const KHM = 'KHM'; //Cambodia
	public const KIR = 'KIR'; //Kiribati
	public const KNA = 'KNA'; //Saint Kitts and Nevis
	public const KOR = 'KOR'; //Korea, Republic of
	public const KWT = 'KWT'; //Kuwait
	public const LAO = 'LAO'; //Lao People's Democratic Republic
	public const LBN = 'LBN'; //Lebanon
	public const LBR = 'LBR'; //Liberia
	public const LBY = 'LBY'; //Libyan Arab Jamahiriya
	public const LCA = 'LCA'; //Saint Lucia
	public const LIE = 'LIE'; //Liechtenstein
	public const LKA = 'LKA'; //Sri Lanka
	public const LSO = 'LSO'; //Lesotho
	public const LTU = 'LTU'; //Lithuania
	public const LUX = 'LUX'; //Luxembourg
	public const LVA = 'LVA'; //Latvia
	public const MAC = 'MAC'; //Macao
	public const MAF = 'MAF'; //Saint Martin (French part)
	public const MAR = 'MAR'; //Morocco
	public const MCO = 'MCO'; //Monaco
	public const MDA = 'MDA'; //Moldova, Republic of
	public const MDG = 'MDG'; //Madagascar
	public const MDV = 'MDV'; //Maldives
	public const MEX = 'MEX'; //Mexico
	public const MHL = 'MHL'; //Marshall Islands
	public const MKD = 'MKD'; //Macedonia, the former Yugoslav Republic of
	public const MLI = 'MLI'; //Mali
	public const MLT = 'MLT'; //Malta
	public const MMR = 'MMR'; //Myanmar
	public const MNE = 'MNE'; //Montenegro
	public const MNG = 'MNG'; //Mongolia
	public const MNP = 'MNP'; //Northern Mariana Islands
	public const MOZ = 'MOZ'; //Mozambique
	public const MRT = 'MRT'; //Mauritania
	public const MSR = 'MSR'; //Montserrat
	public const MTQ = 'MTQ'; //Martinique
	public const MUS = 'MUS'; //Mauritius
	public const MWI = 'MWI'; //Malawi
	public const MYS = 'MYS'; //Malaysia
	public const MYT = 'MYT'; //Mayotte
	public const NAM = 'NAM'; //Namibia
	public const NCL = 'NCL'; //New Caledonia
	public const NER = 'NER'; //Niger
	public const NFK = 'NFK'; //Norfolk Island
	public const NGA = 'NGA'; //Nigeria
	public const NIC = 'NIC'; //Nicaragua
	public const NIU = 'NIU'; //Niue
	public const NLD = 'NLD'; //Netherlands
	public const NOR = 'NOR'; //Norway
	public const NPL = 'NPL'; //Nepal
	public const NRU = 'NRU'; //Nauru
	public const NZL = 'NZL'; //New Zealand
	public const OMN = 'OMN'; //Oman
	public const PAK = 'PAK'; //Pakistan
	public const PAN = 'PAN'; //Panama
	public const PCN = 'PCN'; //Pitcairn
	public const PER = 'PER'; //Peru
	public const PHL = 'PHL'; //Philippines
	public const PLW = 'PLW'; //Palau
	public const PNG = 'PNG'; //Papua New Guinea
	public const POL = 'POL'; //Poland
	public const PRI = 'PRI'; //Puerto Rico
	public const PRK = 'PRK'; //Korea, Democratic People's Republic of
	public const PRT = 'PRT'; //Portugal
	public const PRY = 'PRY'; //Paraguay
	public const PSE = 'PSE'; //Palestinian Territory, Occupied
	public const PYF = 'PYF'; //French Polynesia
	public const QAT = 'QAT'; //Qatar
	public const REU = 'REU'; //Réunion
	public const ROU = 'ROU'; //Romania
	public const RUS = 'RUS'; //Russian Federation
	public const RWA = 'RWA'; //Rwanda
	public const SAU = 'SAU'; //Saudi Arabia
	public const SDN = 'SDN'; //Sudan
	public const SEN = 'SEN'; //Senegal
	public const SGP = 'SGP'; //Singapore
	public const SGS = 'SGS'; //South Georgia and the South Sandwich Islands
	public const SHN = 'SHN'; //Saint Helena, Ascension and Tristan da Cunha
	public const SJM = 'SJM'; //Svalbard and Jan Mayen
	public const SLB = 'SLB'; //Solomon Islands
	public const SLE = 'SLE'; //Sierra Leone
	public const SLV = 'SLV'; //El Salvador
	public const SMR = 'SMR'; //San Marino
	public const SOM = 'SOM'; //Somalia
	public const SPM = 'SPM'; //Saint Pierre and Miquelon
	public const SRB = 'SRB'; //Serbia
	public const SSD = 'SSD'; //South Sudan
	public const STP = 'STP'; //Sao Tome and Principe
	public const SUR = 'SUR'; //Suriname
	public const SVK = 'SVK'; //Slovakia
	public const SVN = 'SVN'; //Slovenia
	public const SWE = 'SWE'; //Sweden
	public const SWZ = 'SWZ'; //Swaziland
	public const SXM = 'SXM'; //Sint Maarten (Dutch part)
	public const SYC = 'SYC'; //Seychelles
	public const SYR = 'SYR'; //Syrian Arab Republic
	public const TCA = 'TCA'; //Turks and Caicos Islands
	public const TCD = 'TCD'; //Chad
	public const TGO = 'TGO'; //Togo
	public const THA = 'THA'; //Thailand
	public const TJK = 'TJK'; //Tajikistan
	public const TKL = 'TKL'; //Tokelau
	public const TKM = 'TKM'; //Turkmenistan
	public const TLS = 'TLS'; //Timor-Leste
	public const TON = 'TON'; //Tonga
	public const TTO = 'TTO'; //Trinidad and Tobago
	public const TUN = 'TUN'; //Tunisia
	public const TUR = 'TUR'; //Turkey
	public const TUV = 'TUV'; //Tuvalu
	public const TWN = 'TWN'; //Taiwan, Province of China
	public const TZA = 'TZA'; //Tanzania, United Republic of
	public const UGA = 'UGA'; //Uganda
	public const UKR = 'UKR'; //Ukraine
	public const UMI = 'UMI'; //United States Minor Outlying Islands
	public const URY = 'URY'; //Uruguay
	public const USA = 'USA'; //United States
	public const UZB = 'UZB'; //Uzbekistan
	public const VAT = 'VAT'; //Holy See (Vatican City State)
	public const VCT = 'VCT'; //Saint Vincent and the Grenadines
	public const VEN = 'VEN'; //Venezuela, Bolivarian Republic of
	public const VGB = 'VGB'; //Virgin Islands, British
	public const VIR = 'VIR'; //Virgin Islands, U.S.
	public const VNM = 'VNM'; //Viet Nam
	public const VUT = 'VUT'; //Vanuatu
	public const WLF = 'WLF'; //Wallis and Futuna
	public const WSM = 'WSM'; //Samoa
	public const YEM = 'YEM'; //Yemen
	public const ZAF = 'ZAF'; //South Africa
	public const ZMB = 'ZMB'; //Zambia
	public const ZWE = 'ZWE'; //Zimbabwe

}
